name: CSS Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  css-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd janus-frontend
          npm install stylelint stylelint-config-standard --save-dev

      - name: Run Stylelint on CSS files
        run: |
          cd janus-frontend
          npx stylelint "janus-website/**/*.css"
